version: '3.1' 

services:
  jena-fuseki-docker:
    container_name: jena-fuseki-docker
    image: openkbs/jena-fuseki-docker
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    user: "1000:1000"
    environment:
      - CONTAINER_NAME=jena-fuseki-docker
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      # - APP_HOME=${APP_HOME:-/home/developer/app}
      # - APP_MAIN=${APP_MAIN:-setup.sh}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP:-192.168.0.125}
      - DOCKER_HOST_NAME=${DOCKER_HOST_NAME:-aurora}
      # ==== X11 Use only ====
      #- DISPLAY=$DISPLAY
      #- DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      # ==== vnc/no-vnc ====
      #- WINDOW_MANAGER=xfce 
      #- VNC_RESOLUTION=1280x800 
      #- VNC_PW=vncpassword 
    ## -------------------------------
    ## -- Audio sound setup:
    ## -------------------------------
    #group_add:
    #  - audio
    #devices:
    #  - "/dev/snd:/dev/snd"
    ## -------------------------------------------
    ## -- Change to your specific Volumes Mapping:
    ## -------------------------------------------
    volumes:
      ## ==== Common mapping: ====
      - /etc/hosts:/etc/hosts
      - /dev/shm:/dev/shm
      #- /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./certificates:/home/developer/certificates
      ## ==== Use $HOME/data-docker as base directory: ====
      #- $HOME/data-docker/jena-fuseki-docker/data:/home/developer/data
      #- $HOME/data-docker/jena-fuseki-docker/workspace:/home/developer/workspace
      ## ==== Use current directory as root for mapping Volumes: ====
      ## (You need to manually create those child directory: ./data, ./workspace, and others)
      #- ./data:/home/developer/data
      #- ./workspace:/home/developer/workspace
      ## ==== App's additional mapping Volumes: ====
      - /home/user1/data-docker/jena-fuseki-docker/fuseki:/home/developer/fuseki
      - /home/user1/data-docker/jena-fuseki-docker/workspace:/home/developer/workspace

    ## -------------------------------
    ## -- Change to your specific port
    ## -------------------------------
    # ports:
    #   - "12345:12345"
    ports:
      - "13030:3030"

    ## -----------------------------
    ## -- Network setup if needed --
    ## -----------------------------
    # networks:
    #  - dev_network

#volumes:
#    jena-fuseki-docker_volume:
#        external: false

#networks:
#  dev_network:
#    external:
#      name: dev_network


