PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX d3f: <http://d3fend.mitre.org/ontologies/d3fend.owl#>

SELECT *
FROM <http://d3fend.mitre.org/ontologies> 
WHERE {
    ?s ?p ?o .
}
LIMIT 100
